using System.Collections.Generic;
using LightningForge.Chess.Core;
using UnityEditor;
using UnityEngine;

namespace LightningForge.Chess.EditorTools
{
    /// <summary>
    /// Bakes the flat "token" piece set: a low disc with the piece's silhouette raised on
    /// its face, for players who find the sculpted pieces hard to read at a glance.
    ///
    /// The icons are real silhouettes rather than letters because the imported TMP font
    /// (LiberationSans SDF) contains none of the Unicode chess glyphs U+2654 to U+265F.
    /// They are generated by mirroring a half profile into a closed outline and extruding
    /// it, which is the same shape the sculpted piece is turned from, so the two sets read
    /// as the same chess set in two styles.
    /// </summary>
    public static class ChessTokenGenerator
    {
        const string MeshFolder = "Assets/Models/Tokens";
        const string PrefabFolder = "Assets/Prefabs/Tokens";

        const float DiscRadius = 0.40f;
        const float DiscHeight = 0.085f;
        const float IconThickness = 0.022f;
        const float IconHeight = 0.52f;   // target height of the tallest icon, in squares

        [MenuItem("Tools/Chess/Generate Piece Tokens")]
        public static void GenerateMenu()
        {
            Debug.Log(GenerateAll());
        }

        public static string GenerateAll()
        {
            EnsureFolder("Assets/Models");
            EnsureFolder(MeshFolder);
            EnsureFolder("Assets/Prefabs");
            EnsureFolder(PrefabFolder);

            Material white = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/PieceWhite.mat");
            Material black = AssetDatabase.LoadAssetAtPath<Material>("Assets/Materials/PieceBlack.mat");
            Material iconOnWhite = EnsureMaterial("TokenIconDark", new Color(0.075f, 0.068f, 0.062f), 0.45f);
            Material iconOnBlack = EnsureMaterial("TokenIconLight", new Color(0.78f, 0.755f, 0.70f), 0.45f);
            if (white == null || black == null) return "ERROR: piece materials missing";

            Mesh disc = Lathe(DiscProfile(), 48);
            disc.name = "TokenDisc";
            disc = SaveMesh(disc, MeshFolder + "/TokenDisc.asset");

            var types = new[]
            {
                PieceType.Pawn, PieceType.Knight, PieceType.Bishop,
                PieceType.Rook, PieceType.Queen, PieceType.King
            };

            var log = new System.Text.StringBuilder();
            foreach (PieceType type in types)
            {
                Mesh icon = BuildIcon(type);
                icon.name = type + "Icon";
                icon = SaveMesh(icon, MeshFolder + "/" + type + "Icon.asset");

                CreateToken(type, PieceColor.White, disc, icon, white, iconOnWhite);
                CreateToken(type, PieceColor.Black, disc, icon, black, iconOnBlack);

                log.Append(type).Append(" icon verts=").Append(icon.vertexCount)
                   .Append(" size=").Append(icon.bounds.size.ToString("0.00")).Append("\n");
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            return log.ToString();
        }

        static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            int slash = path.LastIndexOf('/');
            AssetDatabase.CreateFolder(path.Substring(0, slash), path.Substring(slash + 1));
        }

        static Material EnsureMaterial(string name, Color color, float smoothness)
        {
            string path = "Assets/Materials/" + name + ".mat";
            Material mat = AssetDatabase.LoadAssetAtPath<Material>(path);
            Shader shader = Shader.Find("Universal Render Pipeline/Lit");
            if (mat == null)
            {
                mat = new Material(shader);
                AssetDatabase.CreateAsset(mat, path);
            }
            mat.shader = shader;
            mat.SetColor("_BaseColor", color);
            mat.SetColor("_Color", color);
            mat.SetFloat("_Smoothness", smoothness);
            EditorUtility.SetDirty(mat);
            return mat;
        }

        static Mesh SaveMesh(Mesh mesh, string path)
        {
            Mesh existing = AssetDatabase.LoadAssetAtPath<Mesh>(path);
            if (existing != null)
            {
                existing.Clear();
                existing.vertices = mesh.vertices;
                existing.triangles = mesh.triangles;
                existing.RecalculateNormals();
                existing.RecalculateBounds();
                EditorUtility.SetDirty(existing);
                return existing;
            }
            AssetDatabase.CreateAsset(mesh, path);
            return mesh;
        }

        static void CreateToken(PieceType type, PieceColor color, Mesh disc, Mesh icon,
            Material discMaterial, Material iconMaterial)
        {
            string path = PrefabFolder + "/" + color + "_" + type + ".prefab";

            var root = new GameObject(color + "_" + type);

            var discGo = new GameObject("Disc");
            discGo.transform.SetParent(root.transform, false);
            discGo.AddComponent<MeshFilter>().sharedMesh = disc;
            discGo.AddComponent<MeshRenderer>().sharedMaterial = discMaterial;

            var iconGo = new GameObject("Icon");
            iconGo.transform.SetParent(root.transform, false);
            iconGo.AddComponent<MeshFilter>().sharedMesh = icon;
            iconGo.AddComponent<MeshRenderer>().sharedMaterial = iconMaterial;
            // Lie the silhouette flat on the disc face, standing slightly proud of it.
            iconGo.transform.localPosition = new Vector3(0f, DiscHeight + IconThickness * 0.5f, 0f);
            iconGo.transform.localRotation = Quaternion.Euler(90f, 0f, 0f);

            // Picking needs a collider on the token itself.
            var collider = root.AddComponent<CapsuleCollider>();
            collider.direction = 1;
            collider.height = DiscHeight * 2f;
            collider.radius = DiscRadius;
            collider.center = new Vector3(0f, DiscHeight * 0.5f, 0f);

            PrefabUtility.SaveAsPrefabAsset(root, path);
            Object.DestroyImmediate(root);
        }

        // ------------------------------------------------------------------ shapes

        static Vector2[] DiscProfile()
        {
            return new[]
            {
                new Vector2(0f, 0f),
                new Vector2(DiscRadius, 0f),
                new Vector2(DiscRadius, DiscHeight * 0.72f),
                new Vector2(DiscRadius * 0.94f, DiscHeight),
                new Vector2(DiscRadius * 0.86f, DiscHeight),
                new Vector2(0f, DiscHeight)
            };
        }

        /// <summary>
        /// Half profiles, mirrored into closed silhouettes. Deliberately simpler than the
        /// sculpted models: an icon has to read at a glance, not carry detail.
        /// </summary>
        static Vector2[] HalfProfile(PieceType type)
        {
            switch (type)
            {
                case PieceType.Pawn:
                    return new[]
                    {
                        new Vector2(0f, 0f), new Vector2(0.30f, 0f), new Vector2(0.26f, 0.09f),
                        new Vector2(0.14f, 0.16f), new Vector2(0.12f, 0.36f), new Vector2(0.19f, 0.42f),
                        new Vector2(0.19f, 0.48f), new Vector2(0.10f, 0.55f), new Vector2(0f, 0.60f)
                    };

                case PieceType.Rook:
                    return new[]
                    {
                        new Vector2(0f, 0f), new Vector2(0.32f, 0f), new Vector2(0.27f, 0.10f),
                        new Vector2(0.19f, 0.18f), new Vector2(0.19f, 0.52f), new Vector2(0.30f, 0.58f),
                        new Vector2(0.30f, 0.76f), new Vector2(0.22f, 0.76f), new Vector2(0.22f, 0.66f),
                        new Vector2(0.11f, 0.66f), new Vector2(0.11f, 0.76f), new Vector2(0f, 0.76f)
                    };

                case PieceType.Bishop:
                    return new[]
                    {
                        new Vector2(0f, 0f), new Vector2(0.31f, 0f), new Vector2(0.26f, 0.09f),
                        new Vector2(0.14f, 0.17f), new Vector2(0.12f, 0.45f), new Vector2(0.22f, 0.52f),
                        new Vector2(0.19f, 0.60f), new Vector2(0.17f, 0.78f), new Vector2(0.08f, 0.90f),
                        new Vector2(0f, 0.94f)
                    };

                case PieceType.Queen:
                    return new[]
                    {
                        new Vector2(0f, 0f), new Vector2(0.33f, 0f), new Vector2(0.28f, 0.10f),
                        new Vector2(0.15f, 0.19f), new Vector2(0.13f, 0.55f), new Vector2(0.26f, 0.64f),
                        new Vector2(0.30f, 0.92f), new Vector2(0.22f, 0.82f), new Vector2(0.16f, 0.95f),
                        new Vector2(0.09f, 0.83f), new Vector2(0f, 0.96f)
                    };

                case PieceType.King:
                    return new[]
                    {
                        new Vector2(0f, 0f), new Vector2(0.33f, 0f), new Vector2(0.28f, 0.10f),
                        new Vector2(0.15f, 0.19f), new Vector2(0.13f, 0.56f), new Vector2(0.26f, 0.64f),
                        new Vector2(0.22f, 0.80f), new Vector2(0.09f, 0.84f), new Vector2(0.09f, 0.90f),
                        new Vector2(0.05f, 0.90f), new Vector2(0.05f, 1.00f), new Vector2(0f, 1.00f)
                    };

                default:
                    return null;   // knight is not symmetric
            }
        }

        /// <summary>The knight is drawn as a full outline: a horse head has no axis of symmetry.</summary>
        static Vector2[] KnightOutline()
        {
            return new[]
            {
                new Vector2(-0.30f, 0f),   new Vector2(0.30f, 0f),
                new Vector2(0.24f, 0.10f), new Vector2(0.12f, 0.18f),
                new Vector2(0.14f, 0.40f), new Vector2(0.30f, 0.50f),
                new Vector2(0.34f, 0.62f), new Vector2(0.26f, 0.70f),
                new Vector2(0.10f, 0.73f), new Vector2(0.05f, 0.88f),
                new Vector2(-0.03f, 0.74f), new Vector2(-0.12f, 0.82f),
                new Vector2(-0.20f, 0.66f), new Vector2(-0.24f, 0.44f),
                new Vector2(-0.16f, 0.24f), new Vector2(-0.24f, 0.10f)
            };
        }

        static Mesh BuildIcon(PieceType type)
        {
            Vector2[] outline = type == PieceType.Knight ? KnightOutline() : Mirror(HalfProfile(type));
            Mesh mesh = Extrude(outline, IconThickness * 0.5f);

            // Normalise so every icon reads at the same visual weight on its token.
            Bounds b = mesh.bounds;
            float scale = b.size.y > 0.0001f ? IconHeight / b.size.y : 1f;
            Vector3[] verts = mesh.vertices;
            for (int i = 0; i < verts.Length; i++)
            {
                verts[i] = new Vector3(
                    (verts[i].x - b.center.x) * scale,
                    (verts[i].y - b.min.y) * scale - IconHeight * 0.5f,
                    verts[i].z);
            }
            mesh.vertices = verts;
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        /// <summary>Turns a half profile (x = radius, y = height) into a closed silhouette.</summary>
        static Vector2[] Mirror(Vector2[] half)
        {
            var outline = new List<Vector2>(half.Length * 2);
            for (int i = 0; i < half.Length; i++) outline.Add(half[i]);
            // Back down the other side, skipping the points that sit on the axis.
            for (int i = half.Length - 1; i >= 0; i--)
            {
                if (Mathf.Abs(half[i].x) < 0.0001f) continue;
                outline.Add(new Vector2(-half[i].x, half[i].y));
            }
            return outline.ToArray();
        }

        // ------------------------------------------------------------------ primitives

        static Mesh Lathe(Vector2[] profile, int segments)
        {
            int rings = profile.Length;
            int cols = segments + 1;
            var vertices = new Vector3[rings * cols];

            for (int r = 0; r < rings; r++)
            {
                for (int c = 0; c < cols; c++)
                {
                    float angle = (float)c / segments * Mathf.PI * 2f;
                    vertices[r * cols + c] = new Vector3(
                        Mathf.Cos(angle) * profile[r].x, profile[r].y, Mathf.Sin(angle) * profile[r].x);
                }
            }

            var tris = new List<int>();
            for (int r = 0; r < rings - 1; r++)
            {
                for (int c = 0; c < segments; c++)
                {
                    int a = r * cols + c, b = a + 1;
                    int d = (r + 1) * cols + c, e = d + 1;
                    tris.Add(a); tris.Add(d); tris.Add(b);
                    tris.Add(b); tris.Add(d); tris.Add(e);
                }
            }

            var mesh = new Mesh();
            mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            mesh.vertices = vertices;
            mesh.triangles = tris.ToArray();
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        /// <summary>
        /// Extrudes a closed outline along Z. Caps and walls get their own vertices so the
        /// creases stay hard; sharing them makes RecalculateNormals smear the silhouette.
        /// </summary>
        static Mesh Extrude(Vector2[] outline, float halfDepth)
        {
            var poly = new List<Vector2>(outline);
            if (SignedArea(poly) < 0f) poly.Reverse();

            int n = poly.Count;
            var verts = new List<Vector3>();
            var tris = new List<int>();

            for (int i = 0; i < n; i++) verts.Add(new Vector3(poly[i].x, poly[i].y, halfDepth));
            for (int i = 0; i < n; i++) verts.Add(new Vector3(poly[i].x, poly[i].y, -halfDepth));

            List<int> cap = Triangulate(poly);
            for (int i = 0; i < cap.Count; i += 3)
            {
                tris.Add(cap[i]); tris.Add(cap[i + 1]); tris.Add(cap[i + 2]);
            }
            for (int i = 0; i < cap.Count; i += 3)
            {
                tris.Add(n + cap[i + 2]); tris.Add(n + cap[i + 1]); tris.Add(n + cap[i]);
            }

            for (int i = 0; i < n; i++)
            {
                int j = (i + 1) % n;
                int b = verts.Count;
                verts.Add(new Vector3(poly[i].x, poly[i].y, halfDepth));
                verts.Add(new Vector3(poly[j].x, poly[j].y, halfDepth));
                verts.Add(new Vector3(poly[j].x, poly[j].y, -halfDepth));
                verts.Add(new Vector3(poly[i].x, poly[i].y, -halfDepth));
                tris.Add(b); tris.Add(b + 2); tris.Add(b + 1);
                tris.Add(b); tris.Add(b + 3); tris.Add(b + 2);
            }

            var mesh = new Mesh();
            mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            mesh.SetVertices(verts);
            mesh.SetTriangles(tris, 0);
            mesh.RecalculateNormals();
            mesh.RecalculateBounds();
            return mesh;
        }

        static float SignedArea(List<Vector2> poly)
        {
            float area = 0f;
            for (int i = 0; i < poly.Count; i++)
            {
                Vector2 a = poly[i], b = poly[(i + 1) % poly.Count];
                area += a.x * b.y - b.x * a.y;
            }
            return area * 0.5f;
        }

        static List<int> Triangulate(List<Vector2> poly)
        {
            var result = new List<int>();
            int n = poly.Count;
            if (n < 3) return result;

            var remaining = new List<int>(n);
            for (int i = 0; i < n; i++) remaining.Add(i);

            int guard = n * n;
            while (remaining.Count > 2 && guard-- > 0)
            {
                bool clipped = false;
                for (int i = 0; i < remaining.Count; i++)
                {
                    int ia = remaining[(i + remaining.Count - 1) % remaining.Count];
                    int ib = remaining[i];
                    int ic = remaining[(i + 1) % remaining.Count];
                    Vector2 a = poly[ia], b = poly[ib], c = poly[ic];
                    if (Cross(b - a, c - b) <= 0f) continue;

                    bool contains = false;
                    for (int k = 0; k < remaining.Count; k++)
                    {
                        int idx = remaining[k];
                        if (idx == ia || idx == ib || idx == ic) continue;
                        if (PointInTriangle(poly[idx], a, b, c)) { contains = true; break; }
                    }
                    if (contains) continue;

                    result.Add(ia); result.Add(ib); result.Add(ic);
                    remaining.RemoveAt(i);
                    clipped = true;
                    break;
                }
                if (!clipped) break;
            }
            return result;
        }

        static float Cross(Vector2 a, Vector2 b) => a.x * b.y - a.y * b.x;

        static bool PointInTriangle(Vector2 p, Vector2 a, Vector2 b, Vector2 c)
        {
            float d1 = Cross(b - a, p - a), d2 = Cross(c - b, p - b), d3 = Cross(a - c, p - c);
            bool neg = d1 < 0f || d2 < 0f || d3 < 0f;
            bool pos = d1 > 0f || d2 > 0f || d3 > 0f;
            return !(neg && pos);
        }
    }
}
